# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0336f8dc1ec96632659808d9d976acb26093301f8ce7a6aefe5e2dd589aa6bf725fa310d0e53b94c298aca8be06678fcd324a486f957a336f340a10e0221359

test:
  secret_key_base: f4a0963ebfbc2340a49b4b90b6a510541276b1e38977822a81b256ebd762d88ce1d12fced99b6cc36f8d6477d81781cc1de5afbce7bf3e8767b7419d2c50ebbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
